export const CharacterRecordV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Whisperspace Character Record V1",
  type: "object",
  required: ["id", "name", "attributes", "skills", "createdAt", "updatedAt", "version"],
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    background: { type: "string" },
    motivation: { type: "string" },
    attributes: {
      type: "object",
      required: ["phys", "ref", "soc", "ment"],
      properties: {
        phys: { type: "number" },
        ref: { type: "number" },
        soc: { type: "number" },
        ment: { type: "number" },
      },
      additionalProperties: false,
    },
    skills: {
      type: "object",
      additionalProperties: { type: "number" },
    },
    learningFocus: {
      type: "string",
      enum: ["combat", "education", "vehicles"],
    },
    skillPoints: { type: "number" },
    stress: {
      type: "object",
      properties: {
        current: { type: "number" },
        cuf: { type: "number" },
        cufLoss: { type: "number" },
      },
      additionalProperties: false,
    },
    wounds: {
      type: "object",
      properties: {
        light: { type: "number" },
        moderate: { type: "number" },
        heavy: { type: "number" },
      },
      additionalProperties: false,
    },
    weapons: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          skillId: { type: "string" },
          useDC: { type: "number" },
          damage: { type: "number" },
          keywords: { type: "array", items: { type: "string" } },
          keywordParams: { type: "object", additionalProperties: { type: ["string", "number", "boolean"] } },
          range: { type: "string" },
          ammo: { type: "number" },
          bulk: { type: "number" },
          req: { type: "string" },
          cost: { type: "number" },
        },
        additionalProperties: false,
      },
    },
    armour: {
      type: "object",
      properties: {
        name: { type: "string" },
        keywords: { type: "array", items: { type: "string" } },
        keywordParams: { type: "object", additionalProperties: { type: ["string", "number", "boolean"] } },
        protection: { type: "number" },
        durability: {
          type: "object",
          properties: {
            current: { type: "number" },
            max: { type: "number" },
          },
          additionalProperties: false,
        },
        bulk: { type: "number" },
        req: { type: "string" },
        cost: { type: "number" },
        special: { type: "string" },
      },
      additionalProperties: false,
    },
    credits: { type: "number" },
    inventory: {
      type: "array",
      items: {
        type: "object",
        required: ["type"],
        properties: {
          id: { type: "string" },
          type: { type: "string", enum: ["item", "cyberware", "narcotics"] },
          name: { type: "string" },
          quantity: { type: "number" },
          uses: { type: "string" },
          bulk: { type: "number" },
          effect: { type: "string" },
          cost: { type: "number" },
          statusEffects: { type: "string" },
          tier: { type: "number" },
          installationDifficulty: { type: "number" },
          requirements: { type: "string" },
          physicalImpact: { type: "string" },
          addictionScore: { type: "number" },
          legality: { type: "string" },
        },
        additionalProperties: false,
      },
    },
    feats: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          statusEffects: { type: "string" },
        },
        additionalProperties: false,
      },
    },
    indomitable: { type: "boolean" },
    notes: { type: "string" },
    createdAt: { type: "string" },
    updatedAt: { type: "string" },
    version: { type: "number", enum: [1] },
  },
  additionalProperties: false,
} as const;
